filter:
    excluded_paths:
        - '*.min.js'
        - 'web/assets/plugins/*'
        - 'web/vendor/*'
        - 'bin/*'
        - 'bower.json'
checks:
    php: true
    javascript: true
build: true