app_admin_setup:
    path:     /setup
    defaults: { _controller: 'AccountController::oneTimeSetupAction' }

app_admin_index:
    path:     /
    defaults: { _controller: 'AccountController::indexAction' }

app_admin_login:
    path:     /login
    defaults: { _controller: 'AccountController::loginAction' }
app_admin_register:
    path:     /register
    defaults: { _controller: 'AccountController::registerAction' }
app_admin_logout:
    path:     /logout
    defaults: { _controller: 'AccountController::logoutAction' }

app_admin_user:
    path:     /user/{username}
    defaults: { _controller: 'AccountController::usersAction' }

app_admin_panel:
    path:     /p/{page}
    defaults: { _controller: 'AccountController::panelAction' }
    requirements:
        page: .+

app_admin_api:
    path:     /api/{function}
    defaults: { _controller: 'AccountController::apiAction' }
