app_account_setup:
    path:     /setup
    defaults: { _controller: 'AccountController::oneTimeSetupAction' }

app_account_index:
    path:     /
    defaults: { _controller: 'AccountController::indexAction' }

app_account_login:
    path:     /login
    defaults: { _controller: 'AccountController::loginAction' }
app_account_register:
    path:     /register
    defaults: { _controller: 'AccountController::registerAction' }
app_account_logout:
    path:     /logout
    defaults: { _controller: 'AccountController::logoutAction' }

app_account_user:
    path:     /user/{username}
    defaults: { _controller: 'AccountController::usersAction' }

app_account_panel:
    path:     /p/{page}
    defaults: { _controller: 'AccountController::panelAction' }

app_account_api:
    path:     /api/{function}
    defaults: { _controller: 'AccountController::apiAction' }
