<!DOCTYPE html>
<html>
<head>
    <title>Maintenance</title>

    <!-- Required Meta Tags Always Come First -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.min.css" />
</head>
<body class="bg-secondary">
<div class="col-md-8 col-lg-6 mt-5 mx-auto">
    <div class="card text-white bg-dark mb-3">
        <div class="card-header">
            <b>The website is currently under maintenance</b>
        </div>
        <div class="card-body">
            <p>We are acutally improving our website.</p>
            <p>Please be patient</p>
        </div>
        <div class="card-footer text-muted">
            <i>Normally we wont take long please just wait a minute and try it then again. If this page is persistant, please contact an Administrator.</i>
        </div>
    </div>
</div>
</body>
</html>
