default:
    resource: 'default/routing.yml'
    host:     www.orbitrondev.org
#    schemes:  [https]
#    defaults:  { _locale: en }
#    prefix:   /{_locale} # TODO: Prefix lets the Framework not find route on request!
#    requirements:
#        _locale: "|en|fr|de|it|es" # put a pipe "|" first

# Just for testing purposes.
app_test:
    path:     /test-page
    defaults: { _controller: 'DefaultController::testAction', 'database': true, 'cron_job': false }

account:
    resource: 'account/routing.yml'
    host:     account.orbitrondev.org
developer:
    resource: 'developer/routing.yml'
    host:     developer.orbitrondev.org
cdn:
    resource: 'cdn/routing.yml'
    host:     cdn.orbitrondev.org

