default:
    resource: 'default/routing.yml'
    host:     www.orbitrondev.org
#    schemes:  [https]
#    defaults:  { _locale: en }
#    prefix:   /{_locale} # TODO: Prefix lets the Framework not find route on request!
#    requirements:
#        _locale: "|en|fr|de|it|es" # put a pipe "|" first

# Just for testing purposes.
app_test:
    path:     /test-page
    defaults: { _controller: 'TestController::indexAction', 'database': true, 'cron_job': false }
account_test:
    path:     /test-page
    defaults: { _controller: 'TestController::indexAction', 'database': true, 'cron_job': false }
    host:     account.orbitrondev.org

account:
    resource: 'account/routing.yml'
    host:     account.orbitrondev.org
blog:
    resource: 'blog/routing.yml'
    host:     blog.orbitrondev.org
cloud:
    resource: 'cloud/routing.yml'
    host:     cloud.orbitrondev.org
forum:
    resource: 'forum/routing.yml'
    host:     forum.orbitrondev.org
wiki:
    resource: 'wiki/routing.yml'
    host:     wiki.orbitrondev.org
developer:
    resource: 'developer/routing.yml'
    host:     developer.orbitrondev.org
cdn:
    resource: 'cdn/routing.yml'
    host:     cdn.orbitrondev.org

