app_store_index:
    path:     /
    defaults: { _controller: 'StoreController::indexAction' }
app_store_new:
    path:     /new-store
    defaults: { _controller: 'StoreController::newStoreAction' }

app_store_store_index:
    path:     /{store}
    defaults: { _controller: 'StoreController::storeIndexAction' }
app_store_store_product:
    path:     /{store}/product/{product}
    defaults: { _controller: 'StoreController::storeProductAction' }
app_store_store_checkout:
    path:     /{store}/checkout
    defaults: { _controller: 'StoreController::storeCheckoutAction' }
app_store_store_do_order:
    path:     /{store}/do-order
    defaults: { _controller: 'StoreController::storeDoOrderAction' }
app_store_store_do_check_voucher:
    path:     /{store}/do-check-voucher
    defaults: { _controller: 'StoreController::storeDoCheckVoucherAction' }
app_store_store_do_remove_to_cart:
    path:     /{store}/do-remove-from-cart
    defaults: { _controller: 'StoreController::storeDoRemoveToCartAction' }
app_store_store_search:
    path:     /{store}/search
    defaults: { _controller: 'StoreController::storeSearchAction' }
app_store_store_admin:
    path:     /{store}/admin/{page}
    defaults: { _controller: 'StoreController::storeAdminAction' }
